### ISSUE TITLE
Python Dependencies Broken on RHEL7

### ISSUE THREAD

**Issue by fuzzyTew** [jatin-cbs/Lutris-RHEL-CentOS7#2]
EDITED to summarize.

It looks like lutris expects python 3.6 but doesn't list python36 as a dependency.  RHEL7 mostly only has python libraries available for python 3.4.  Additionally, Python 3.6 only launches if run as `python36`.

```
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
ImportError: No module named 'lutris'
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.6 (Maipo)
$ rpmquery lutris
lutris-0.4.23-1.el7.noarch
$ python3 -s
Python 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sys import path
>>> path
['', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/usr/lib64/python3.4/site-packages', '/usr/lib/python3.4/site-packages']
```

To get lutris to run on RHEL7 from this rpm, I had to move the libraries from lib/python-3.6 to lib/python-3.6 and also install `python34-gobject` and `python34-PyYAML`.

**Comment by fuzzyTew** [comment]
It turns out on RHEL7, the solution is not to use python 3.6, but rather to use python 3.4 .  There is no python36-gobject available in the repos, there is a python34-gobject.

**Comment by Saladin1812** [comment]
I have included `python34-gobject` and `PyYAML` in the RPM itself, not sure why you had to install those. And this is a known issue that you have to move package from 3.6 to 3.4 this is a known issue. I tried changing the spec file and change the directories but that comes up with 100s of more issues. I have included this known issue in the readme tho ! If you can help you can open a pull request :)

**Comment by Saladin1812** [comment]
The new sh file is based on python 3.6 :)
