### ISSUE TITLE
Spec files in repository?

### ISSUE THREAD

**Issue by fuzzyTew** [jatin-cbs/Lutris-RHEL-CentOS7#3]
If you could include the spec files in the repository, we could submit patches to them to fix bugs!

**Comment by Saladin1812** [comment]
all though you can simply edit spec file by 
`rpmrebuild -enp packagename` command but still I will try including it in the repository.

**Comment by Saladin1812** [comment]
You need to install rpm rebuild first* 
` sudo yum install rpmrebuild`
