### ISSUE TITLE
Distributing the sh file

### ISSUE THREAD

**Issue by Saladin1812** [jatin-cbs/Lutris-RHEL-CentOS7#5]
@strycore @tannisroot For ease of installation I created this sh script for CentOS users, it will be great to distribute this sh via lutris website or any link. They simply have to run this sh script to get lutris up and running on centos. This will even make easier for me to test future versions in other branch and release sh once a version is tested and working.

**Comment by Saladin1812** [comment]
@strycore @tannisroot just make sure if its possible.

**Comment by strycore** [comment]
I can link to the script from the download page if that's enough?

**Comment by Saladin1812** [comment]
Yes that would be enough @strycore

**Comment by Saladin1812** [comment]
@strycore @tannisroot yes you can surely link the script on the download page. No instructions needed now..

**Comment by Saladin1812** [comment]
@strycore :)

**Comment by strycore** [comment]
Download page updated with a CentOS section, let me know if you want to make some changes to the text (you can submit a PR directly to download.html on the website)

**Comment by Saladin1812** [comment]
thanks :)
