### ISSUE TITLE
Core dumped (lutris 5 script)

### ISSUE THREAD

**Issue by IanTrudel** [jatin-cbs/Lutris-RHEL-CentOS7#6]
The list of things that went wrong here is way too long. The first thing is that it uses IUS repo that seems to be hardly reachable. Epel is usually the go-to repo. The second thing is that it forces install python34 while I already had it and have/use python36 anyway. Basically, it's a huge mess for me to clean up and no Lutris. :(

**Comment by IanTrudel** [comment]
Hmmm. There seem to be a problem with IUS that is unrelated to your script. Still, the script is not working in any case.

**Comment by Saladin1812** [comment]
Is the script giving an error ? logs would be helpful.

**Comment by Saladin1812** [comment]
EPEL repo just didnt work when i tested, I also give first preference to repos like EPEL, RPM fusion, nux and then the others (in that order). Send me the logs https://pastebin.com/ or an SS.

**Comment by IanTrudel** [comment]
I am not daring to reinstall to get the log file. o_O

**Comment by IanTrudel** [comment]
It wasn't a good idea. It really wasn't.

```
lutris -d
INFO     2019-06-15 22:03:49,798 [application.do_command_line:219]:Running Lutris 0.5.1.2
INFO     2019-06-15 22:03:49,798 [startup.check_driver:55]:Using NVIDIA drivers 430.26 for x86_64
INFO     2019-06-15 22:03:49,799 [startup.check_driver:59]:GPU: GeForce GTX 660M
INFO     2019-06-15 22:03:49,799 [startup.check_driver:76]:GPU: 10DE:0FD4 1043:2115 using nvidia drivers
[1]    21039 segmentation fault (core dumped)  lutris -d
```

**Comment by Saladin1812** [comment]
maybe some update broke it now "__" How is it breaking the OS ? I tested it on a VM its by no means breaking the OS tho you can always change vendors from IUS to EPEL if you want to managing python versions is not hard if you are using python for other purposes.. @BackOrder

**Comment by Saladin1812** [comment]
@BackOrder I will test the bug on the VM till then you can go to the master branch and try lutis 4.23 :) It will work just fine..

**Comment by IanTrudel** [comment]
Lutris doesn't like my multiple libstdc++. Normally `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/libstdc++.so.6.0.22 lutris` would be enough but it is not working. Lutris will only work when the library above is symlink to `/usr/lib64/libstdc++.so.6`. Any idea?

**Comment by Saladin1812** [comment]
you can create a symlink of so.6.0.22 to so.6 I can add that to the script but i have to make sure i doesnt break things up.

**Comment by IanTrudel** [comment]
> you can create a symlink of so.6.0.22 to so.6 I can add that to the script but i have to make sure i doesnt break things up.

This is exactly what I did but not ideal. Where are the Lutris files located? Perhaps the library can be copied along other libraries.

**Comment by Saladin1812** [comment]
Its inside python3.6/site-packages

**Comment by Saladin1812** [comment]
Im currently working on to fix python conflicts on fresh installs as IUS and EPEL are both on exact same python version, In RHEL 8 this problem would atleast be eliminated.

**Comment by Saladin1812** [comment]
I resolved the conflict between IUS and EPEL for python36. I didnt get any errors on launching maybe a system specific issue, I can confirm that its working on a fresh installation.

**Comment by IanTrudel** [comment]
You are awesome! I will try whenever I got free time and report back to you.

**Comment by IanTrudel** [comment]
I installed Lutris based on some portions your script but without actually running the script. I'm still a little scared to use it considering the messed it made last time. So Lutris works.

One thing I would have liked is to use python36 from EPEL instead IUS. It still requires to use the one from IUS and had to removed the EPEL one.

**Comment by IanTrudel** [comment]
Please, be noted that it's impossible to install some core CentOS programs such as mock (mockbuild), that allows to rebuild rpm source packages, without EPEL python36.  Do you have any idea how we could have Lutris using EPEL version instead? That would save the world from a whole lot of problems.

**Comment by Saladin1812** [comment]
See the RHEL 8 RPM its clean rpm no script needed because everything is in the Official repos or EPEL so there is no problem, but for  Centos or rhel 7 not all dependencies are satisfied with EPEL so i had to use IUS.. @BackOrder

**Comment by IanTrudel** [comment]
What are the other required packages from IUS besides python?

**Comment by Saladin1812** [comment]
There is python3-evdev python3-pillow and few more python 3 libraries..

**Comment by IanTrudel** [comment]
Hmmm. This is a tough one. Though pillow is available on EPEL.

**Comment by IanTrudel** [comment]
The python packages are installed through pip from my understanding. For example, `yum list installed | grep evdev` does not return any python3-evdev. Seems like it could absolutely use EPEL python36 without problems. I had previously manually installed the python packages on EPEL version from your instructions.

**Comment by Saladin1812** [comment]
I am not sure tho but I also give first preference to EPEL but in CentOS 7 for some reason EPEL python packages were not working for some reason.

**Comment by IanTrudel** [comment]
May I suggest you to give it another try? Perhaps in a virtual machine or something. As previously mentioned, I had manually performed the tasks from your script on EPEL python. It had no such problems. Perhaps devs fixed the thing since you last tried.

**Comment by Saladin1812** [comment]
Oh ok i will give it a try in a VM

**Comment by IanTrudel** [comment]
Hi @jatin-cbs ! Python3 package is now superseding python36 and python36u in the base repository. Take a look.
