### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by MCMCMC** [jatin-cbs/Lutris-RHEL-CentOS7#8]
I've tried to install it multiple times, but it didn't work. I have remove any versions of lutris (there were none, but the attempts I made sure). I have installed EPEL and RPM Fusion.

I get the following errors:

```
Error: Package: lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
        Requires: python36u-devel
        Available: python36-devel-3.6.8-2.el7.ius.x86_64 (ius)
                python36u-devel = 3.6.8-2.el7.ius
        Available: python36u-devel-3.6.8-1.el7.ius.x86_64 (ius)
                python36u-devel = 3.6.8-1.el7.ius
Error: Package: lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
        Requires: python36u
        Available: python36-3.6.8-2.el7.ius.x86_64 (ius)
                python36u = 3.6.8-2.el7.ius
        Available: python36u-3.6.8-1.el7.ius.x86_64 (ius)
                python36u = 3.6.8-1.el7.ius
Error: Package: lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
        Requires: python36u-pip
        Available: python36-pip-9.0.1-2.el7.ius.noarch (ius)
                python36u-pip = 9.0.1-2.el7.ius
        Available: python36u-pip-9.0.1-1.ius.el7.noarch (ius)
                python36u-pip = 9.0.1-1.ius.el7
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest
```

**Comment by Saladin1812** [comment]
Try old lutris from the master branch it uses python from official repository this actually may have some problems due to changing the defsult python version all tho you can use centos 8 which has lutris 5.2.1 and I can officialy provide support for rhel and centos 8 as i have those installed on my main machine.. Try installing from the master branch of this repo @MCMCMC

**Comment by Saladin1812** [comment]
Also make sure to remove IUS repo before installing the RPM. @MCMCMC

**Comment by Saladin1812** [comment]
Fixed the bug remove IUS repo or any other third party and with single rpm easy to install
