### ISSUE TITLE
Lutris v0.5.4 is out

### ISSUE THREAD

**Issue by IanTrudel** [jatin-cbs/Lutris-RHEL-CentOS7#9]
Are we going to get an update for Lutris on CentOS? Perhaps something a bit more agnostic than in the past. Python3 package is now superseding python36 and python36u in the base repository.

**Comment by Saladin1812** [comment]
Thats quite true but i dont have centos 7 installed on my machine but i would install it on a VM and try.. I currently maintain lutris for RHEL 8 lutris 5.2.1 is available for rhel 8 .. But for centos 7 its a bit hard as you have to change the whole default python version.

**Comment by IanTrudel** [comment]
Long time no see! Actually, good news, Lutris from the official repo now builds and installs on CentOS. Thank you. :)

**Comment by Saladin1812** [comment]
https://github.com/jatin-cbs/Lutris-RHEL-CentOS-8
You can download it from here :) as python 3.6 is the default in RHEL 8 it works nicely without hassle with python versions. @BackOrder

**Comment by Saladin1812** [comment]
@BackOrder I currently built Lutris 5.2 for RHEL 8/ CentOS 8
Would be updating to 5.3 or 5.4 once the python 3.7 lands in RHEL 8 as per minimum requirement.

**Comment by Saladin1812** [comment]
@BackOrder Hi there you were right now we dont need IUS i have all the dependencies in a single rpm file and its working :) just install the rpm of lutris 5.1.2 provided in one easy single dnf install command. I will update it to 5.2 soon but for later versions we need python 3.7.

**Comment by Saladin1812** [comment]
@BackOrder the thing was IUS conflicts with epel its better to use things from epel itself. But at that time epel didnt had python 3.6  but now it does work out of the box 😉

**Comment by IanTrudel** [comment]
No worries, you have done plenty for us! Now things just got easier. Thank you @jatin-cbs
